#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent.parent;b=R/'experiments/vm6-locked-2026'
raw=json.loads((b/'raw-diff.json').read_text());cfg=json.loads((b/'structural-diff.json').read_text());proof=json.loads((b/'transition-proof.json').read_text())
assert raw['hamming_distance']==cfg['structural_difference_count']==0 and proof['all_passed']
s=dict(kind='post-fit VM6 implementation lock',fuse_distance=0,canonical_difference_count=0,transition_proofs=49,native_fitter_fuse_distance=json.loads((R/'experiments/ise-readback-2026/raw-diff.json').read_text())['hamming_distance'],native_fitter_bit_identity=False,implementation_locked_bit_identity=True,hardware_programmed=False,security_outside_QF_verified=False,template='recovered/amplcpld.ptlock.json',output='recovered/amplcpld_implementation_locked.jed',output_sha256=hashlib.sha256((R/'recovered/amplcpld_implementation_locked.jed').read_bytes()).hexdigest())
(R/'reports/implementation_lock_status.json').write_text(json.dumps(s,indent=2)+'\n')
(R/'reports/implementation_lock.md').write_text('# Explicit VM6 implementation locking\n\nAdditional Polish version: [implementation_lock.pl.md](implementation_lock.pl.md).\n\n**The final output has zero differences across all 55,341 QF fuses and zero canonical configuration differences against `pm_cpld_gold_2026.jed`.** Output: `recovered/amplcpld_implementation_locked.jed`.\n\nPipeline: recovered VHDL + UCF → XST → ngdbuild → cpldfit → native VM6 → `lock_vm6_placement.py` + `amplcpld.ptlock.json` → locked VM6 → Xilinx hprep6 → JED.\n\nThis is **not** a fuse-identical native fitter result or recovery of the historical source/options. The native fitter still produces 346 differences. The additional backend locks physical PLA rows in FB1/FB2 and uses an equivalent literal cover for the highest counter bit’s T input. The template comes from the decoded golden configuration and contains AND equations, not just placement coordinates. The golden JED or ready-made fuse bits are not copied into the output: hprep6 generates JED from the actual modified fitter VM6.\n\nZIA, clocks, initialization, all macrocell/IOB/global fields come from the native fit and must already match. Every other sum cover must agree before locking. The differing c_count9 T input is checked with SAT before replacement. The wrapper re-proves all 49 native transitions before locking and all 49 after JED generation. A negative test rejects a changed REG_INIT without creating output. The original SHA-256 remains preserved.\n\nArtifacts: `experiments/vm6-locked-2026/design.vm6`, `design.lock.json`, raw/canonical comparisons and the 49/49 UNSAT proof. Actual vendor log: `experiments/logs/vm6-locked-hprep6.log`. Reproduce with `make reproduce` for the complete workflow or `make implementation-locked` for native build plus lock. Guards, comparison and proof failures stop the workflow.\n\nThe final JED matches all QF fuses. Text headers/timestamps and the transmission checksum can differ because hprep6 creates its own JEDEC container. Security/DONE/USERCODE outside QF are not confirmed. No hardware was programmed and no board timing measurements were performed.\n\nISE settings are loaded in a subshell used only for hprep6, preventing legacy ISE libraries from interfering with modern Z3. The initial libz3.so failure is preserved in `locked-pipeline.log`; the corrected pipeline passed.\n')
print(json.dumps(s,indent=2))

for path in ['reports/final_equivalence.md','reports/readback-2026/final_equivalence.md']:
 p=R/path
 text=p.read_text().split('\n## Additional implementation lock')[0]
 text+='\n## Additional implementation lock\n\nExplicit PLA locking in VM6 followed by Xilinx hprep6 produced 0/55341 fuse differences and 0 canonical differences. This additional backend uses a golden-derived allocation/equation template; the native fitter alone is not fuse-identical. Locked JED: recovered/amplcpld_implementation_locked.jed. Method and proof scope: reports/implementation_lock.md.\n'
 p.write_text(text)
