## Bank 64
set_property IOSTANDARD LVCMOS18 [get_ports ADC_*]
set_property PACKAGE_PIN AF24 [get_ports {ADC_CLK}]
set_property PACKAGE_PIN AF25 [get_ports {ADC_RESET}]
set_property PACKAGE_PIN AC17 [get_ports {ADC_MOSI}]
set_property PACKAGE_PIN AA17 [get_ports {ADC_MISO}]
set_property PACKAGE_PIN AF23 [get_ports {ADC_EN2}]
set_property PACKAGE_PIN AF20 [get_ports {ADC_EN1}]

set_property IOSTANDARD LVDS [get_ports CLK_B_OUT_P]
set_property DIFF_TERM_ADV TERM_100 [get_ports CLK_B_OUT_P]
set_property PACKAGE_PIN AB21 [get_ports CLK_B_OUT_P]

set_property IOSTANDARD LVDS [get_ports {ADC_BA_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADC_BA_P*}]
set_property PACKAGE_PIN AD23 [get_ports {ADC_BA_P[0]}]
set_property PACKAGE_PIN AE22 [get_ports {ADC_BA_P[1]}]
set_property PACKAGE_PIN AD21 [get_ports {ADC_BA_P[2]}]
set_property PACKAGE_PIN AF18 [get_ports {ADC_BA_P[3]}]
set_property PACKAGE_PIN AE17 [get_ports {ADC_BA_P[4]}]
set_property PACKAGE_PIN AC18 [get_ports {ADC_BA_P[5]}]
set_property PACKAGE_PIN AD16 [get_ports {ADC_BA_P[6]}]

set_property IOSTANDARD LVDS [get_ports {ADC_BB_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADC_BB_P*}]
set_property PACKAGE_PIN AD24 [get_ports {ADC_BB_P[0]}]
set_property PACKAGE_PIN AA22 [get_ports {ADC_BB_P[1]}]
set_property PACKAGE_PIN Y20  [get_ports {ADC_BB_P[2]}]
set_property PACKAGE_PIN AA19 [get_ports {ADC_BB_P[3]}]
set_property PACKAGE_PIN AA20 [get_ports {ADC_BB_P[4]}]
set_property PACKAGE_PIN AB24 [get_ports {ADC_BB_P[5]}]
set_property PACKAGE_PIN AC22 [get_ports {ADC_BB_P[6]}]

set_property IOSTANDARD LVDS [get_ports {PLL*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {PLL_clk_p}]
set_property PACKAGE_PIN AD20 [get_ports {PLL_clk_p}]

set_property IOSTANDARD LVCMOS18 [get_ports OSC1]
set_property PACKAGE_PIN AC19 [get_ports OSC1]

## Bank 66
set_property IOSTANDARD LVDS [get_ports CLK_A_OUT_P]
set_property DIFF_TERM_ADV TERM_100 [get_ports CLK_A_OUT_P]
set_property PACKAGE_PIN K22 [get_ports CLK_A_OUT_P]

set_property IOSTANDARD LVDS [get_ports {ADC_AA_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADC_AA_P*}]
set_property PACKAGE_PIN H21 [get_ports {ADC_AA_P[0]}]
set_property PACKAGE_PIN K21 [get_ports {ADC_AA_P[1]}]
set_property PACKAGE_PIN G24 [get_ports {ADC_AA_P[2]}]
set_property PACKAGE_PIN F24 [get_ports {ADC_AA_P[3]}]
set_property PACKAGE_PIN H23 [get_ports {ADC_AA_P[4]}]
set_property PACKAGE_PIN H26 [get_ports {ADC_AA_P[5]}]
set_property PACKAGE_PIN J23 [get_ports {ADC_AA_P[6]}]

set_property IOSTANDARD LVDS [get_ports {ADC_AB_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADC_AB_P*}]
set_property PACKAGE_PIN L20 [get_ports {ADC_AB_P[0]}]
set_property PACKAGE_PIN K25 [get_ports {ADC_AB_P[1]}]
set_property PACKAGE_PIN M25 [get_ports {ADC_AB_P[2]}]
set_property PACKAGE_PIN M19 [get_ports {ADC_AB_P[3]}]
set_property PACKAGE_PIN L24 [get_ports {ADC_AB_P[4]}]
set_property PACKAGE_PIN L22 [get_ports {ADC_AB_P[5]}]
set_property PACKAGE_PIN J25 [get_ports {ADC_AB_P[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports Gate_STR1_i]
set_property PACKAGE_PIN E26 [get_ports Gate_STR1_i]

## Bank 65
set_property IOSTANDARD LVDS [get_ports Event*]
set_property DIFF_TERM_ADV TERM_100 [get_ports Event*]
set_property PACKAGE_PIN AA24 [get_ports Event1_P]
set_property PACKAGE_PIN Y25  [get_ports Event2_P]
set_property PACKAGE_PIN W25  [get_ports Event3_P]
set_property PACKAGE_PIN U26  [get_ports Event4_P]

set_property IOSTANDARD LVDS [get_ports Calibration*]
set_property PACKAGE_PIN T25 [get_ports Calibration_P]

## Bank 83
set_property IOSTANDARD LVCMOS33 [get_ports S*1]
set_property IOSTANDARD LVCMOS33 [get_ports X*IO*]
set_property PACKAGE_PIN H14 [get_ports {S31[0]}]
set_property PACKAGE_PIN G14 [get_ports {S21[0]}]
set_property PACKAGE_PIN J15 [get_ports {XIO[2]}]
set_property PACKAGE_PIN J14 [get_ports {S41[0]}]
set_property PACKAGE_PIN G12 [get_ports {XIO[1]}]
set_property PACKAGE_PIN F12 [get_ports {XIO[0]}]
set_property PACKAGE_PIN F14 [get_ports {S11[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports INT_*]
set_property PACKAGE_PIN D14 [get_ports INT_A_G_DRV_P]
set_property PACKAGE_PIN C14 [get_ports INT_A_G_DRV_N]
set_property PACKAGE_PIN C13 [get_ports INT_B_G_DRV_P]
set_property PACKAGE_PIN B14 [get_ports INT_B_G_DRV_N]

## Bank 84
set_property IOSTANDARD LVCMOS33 [get_ports {LA1*}]
set_property PACKAGE_PIN AC13 [get_ports {LA1[0]}]
set_property PACKAGE_PIN AD13 [get_ports {LA1[1]}]
set_property PACKAGE_PIN AF13 [get_ports {LA1[2]}]
set_property PACKAGE_PIN AE13 [get_ports {LA1[3]}]
set_property PACKAGE_PIN AB14 [get_ports {LA1[4]}]
set_property PACKAGE_PIN AF14 [get_ports {LA1[5]}]
set_property PACKAGE_PIN AD14 [get_ports {LA1[6]}]
set_property PACKAGE_PIN AE15 [get_ports {LA1[7]}]
set_property PACKAGE_PIN AF15 [get_ports {LA1[8]}]
set_property PACKAGE_PIN AC14 [get_ports {LA1[9]}]
set_property PACKAGE_PIN AD15 [get_ports {LA1[10]}]
set_property PACKAGE_PIN AA14 [get_ports {LA1[11]}]
set_property PACKAGE_PIN Y15  [get_ports {LA1[12]}]
set_property PACKAGE_PIN AA15 [get_ports {LA1[13]}]
set_property PACKAGE_PIN AB15 [get_ports {LA1[14]}]
set_property PACKAGE_PIN AB16 [get_ports {LA1[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports LACK1]
set_property PACKAGE_PIN W16 [get_ports LACK1]

set_property IOSTANDARD LVCMOS33 [get_ports CFD_OUT]
set_property PACKAGE_PIN Y16 [get_ports CFD_OUT]

set_property IOSTANDARD LVCMOS33 [get_ports Gate_STR1_o]
set_property PACKAGE_PIN Y13 [get_ports Gate_STR1_o]

## Bank 85
set_property IOSTANDARD LVCMOS33 [get_ports {LA0*}]
set_property PACKAGE_PIN C11 [get_ports {LA0[0]}]
set_property PACKAGE_PIN B11 [get_ports {LA0[1]}]
set_property PACKAGE_PIN D11 [get_ports {LA0[2]}]
set_property PACKAGE_PIN B10 [get_ports {LA0[3]}]
set_property PACKAGE_PIN A10 [get_ports {LA0[4]}]
set_property PACKAGE_PIN D10 [get_ports {LA0[5]}]
set_property PACKAGE_PIN B9  [get_ports {LA0[6]}]
set_property PACKAGE_PIN A9  [get_ports {LA0[7]}]
set_property PACKAGE_PIN C9  [get_ports {LA0[8]}]
set_property PACKAGE_PIN D9  [get_ports {LA0[9]}]
set_property PACKAGE_PIN E10 [get_ports {LA0[10]}]
set_property PACKAGE_PIN E11 [get_ports {LA0[11]}]
set_property PACKAGE_PIN F9  [get_ports {LA0[12]}]
set_property PACKAGE_PIN F10 [get_ports {LA0[13]}]
set_property PACKAGE_PIN G9  [get_ports {LA0[14]}]
set_property PACKAGE_PIN G10 [get_ports {LA0[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports LACK0]
set_property PACKAGE_PIN G11 [get_ports LACK0]

