## Bank 64
set_property IOSTANDARD LVCMOS18 [get_ports {ADC_*}]
set_property PACKAGE_PIN AF24 [get_ports {ADC_CLK}]
set_property PACKAGE_PIN AF25 [get_ports {ADC_RESET}]
set_property PACKAGE_PIN AC17 [get_ports {ADC_DATA}]
set_property PACKAGE_PIN AA17 [get_ports {ADC_DOUT}]
set_property PACKAGE_PIN AF23 [get_ports {ADC_EN2}]
set_property PACKAGE_PIN AF20 [get_ports {ADC_EN1}]

set_property IOSTANDARD LVDS [get_ports {CLKB_OUT_P}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {CLKB_OUT_P}]
set_property PACKAGE_PIN AB21 [get_ports {CLKB_OUT_P}]

set_property IOSTANDARD LVDS [get_ports {ADCBA_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADCBA_*}]
set_property PACKAGE_PIN AD23 [get_ports {ADCBA_D0_P}]
set_property PACKAGE_PIN AE22 [get_ports {ADCBA_D2_P}]
set_property PACKAGE_PIN AD21 [get_ports {ADCBA_D4_P}]
set_property PACKAGE_PIN AF18 [get_ports {ADCBA_D6_P}]
set_property PACKAGE_PIN AE17 [get_ports {ADCBA_D8_P}]
set_property PACKAGE_PIN AC18 [get_ports {ADCBA_D10_P}]
set_property PACKAGE_PIN AD16 [get_ports {ADCBA_D12_P}]

set_property IOSTANDARD LVDS [get_ports {ADCBB_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADCBB_*}]
set_property PACKAGE_PIN AD24 [get_ports {ADCBB_D0_P}]
set_property PACKAGE_PIN AB22 [get_ports {ADCBB_D2_P}]
set_property PACKAGE_PIN Y20 [get_ports {ADCBB_D4_P}]
set_property PACKAGE_PIN AB19 [get_ports {ADCBB_D6_P}]
set_property PACKAGE_PIN AB20 [get_ports {ADCBB_D8_P}]
set_property PACKAGE_PIN AB24 [get_ports {ADCBB_D10_P}]
set_property PACKAGE_PIN AC22 [get_ports {ADCBB_D12_P}]

set_property IOSTANDARD LVDS [get_ports {PLL_CLK_P}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {PLL_CLK_P}]
set_property PACKAGE_PIN AD20 [get_ports {PLL_CLK_P}]

set_property IOSTANDARD LVCMOS18 [get_ports {OSC1}]
set_property PACKAGE_PIN AC19 [get_ports {OSC1}]

## Bank 66
set_property IOSTANDARD LVDS [get_ports {CLKA_OUT_P}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {CLKA_OUT_P}]
set_property PACKAGE_PIN K22 [get_ports {CLKA_OUT_P}]

set_property IOSTANDARD LVDS [get_ports {ADCAA_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADCAA_*}]
set_property PACKAGE_PIN H21 [get_ports {ADCAA_D0_P}]
set_property PACKAGE_PIN K21 [get_ports {ADCAA_D2_P}]
set_property PACKAGE_PIN G24 [get_ports {ADCAA_D4_P}]
set_property PACKAGE_PIN F24 [get_ports {ADCAA_D6_P}]
set_property PACKAGE_PIN H23 [get_ports {ADCAA_D8_P}]
set_property PACKAGE_PIN H26 [get_ports {ADCAA_D10_P}]
set_property PACKAGE_PIN J23 [get_ports {ADCAA_D12_P}]

set_property IOSTANDARD LVDS [get_ports {ADCAB_*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {ADCAB_*}]
set_property PACKAGE_PIN L20 [get_ports {ADCAB_D0_P}]
set_property PACKAGE_PIN K25 [get_ports {ADCAB_D2_P}]
set_property PACKAGE_PIN M25 [get_ports {ADCAB_D4_P}]
set_property PACKAGE_PIN M19 [get_ports {ADCAB_D6_P}]
set_property PACKAGE_PIN L24 [get_ports {ADCAB_D8_P}]
set_property PACKAGE_PIN L22 [get_ports {ADCAB_D10_P}]
set_property PACKAGE_PIN J25 [get_ports {ADCAB_D12_P}]

set_property IOSTANDARD LVCMOS18 [get_ports {Gate_STR1_i}]
set_property PACKAGE_PIN E26 [get_ports {Gate_STR1_i}]

## Bank 65
set_property IOSTANDARD LVDS [get_ports {Event*}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {Event*}]
set_property PACKAGE_PIN AA24 [get_ports {Event1_P}]
set_property PACKAGE_PIN Y25 [get_ports {Event2_P}]
set_property PACKAGE_PIN W25 [get_ports {Event3_P}]
set_property PACKAGE_PIN U20 [get_ports {Event4_P}]

set_property IOSTANDARD LVDS [get_ports {Calibration*}]
set_property PACKAGE_PIN T25 [get_ports {Calibration_P}]

## Bank 83
set_property IOSTANDARD LVCMOS33 [get_ports {S*1}]
set_property IOSTANDARD LVCMOS33 [get_ports {X*IO*}]
set_property PACKAGE_PIN H14 [get_ports {S31}]
set_property PACKAGE_PIN G14 [get_ports {S21}]
set_property PACKAGE_PIN J15 [get_ports {X4IO1}]
set_property PACKAGE_PIN J14 [get_ports {S41}]
set_property PACKAGE_PIN G12 [get_ports {X2IO2}]
set_property PACKAGE_PIN F12 [get_ports {X2IO1}]
set_property PACKAGE_PIN F14 [get_ports {S11}]

set_property IOSTANDARD LVCMOS33 [get_ports {INT_*}]
set_property PACKAGE_PIN D14 [get_ports {INT_A_G_DRV_P}]
set_property PACKAGE_PIN C14 [get_ports {INT_A_G_DRV_N}]
set_property PACKAGE_PIN C13 [get_ports {INT_B_G_DRV_P}]
set_property PACKAGE_PIN B14 [get_ports {INT_B_G_DRV_N}]

## Bank 84
set_property IOSTANDARD LVCMOS33 [get_ports {LA1_*}]
set_property PACKAGE_PIN AC13 [get_ports {LA1_0}]
set_property PACKAGE_PIN AD13 [get_ports {LA1_1}]
set_property PACKAGE_PIN AF13 [get_ports {LA1_2}]
set_property PACKAGE_PIN AE13 [get_ports {LA1_3}]
set_property PACKAGE_PIN AB14 [get_ports {LA1_4}]
set_property PACKAGE_PIN AF14 [get_ports {LA1_5}]
set_property PACKAGE_PIN AD14 [get_ports {LA1_6}]
set_property PACKAGE_PIN AE15 [get_ports {LA1_7}]
set_property PACKAGE_PIN AF15 [get_ports {LA1_8}]
set_property PACKAGE_PIN AC14 [get_ports {LA1_9}]
set_property PACKAGE_PIN AD15 [get_ports {LA1_10}]
set_property PACKAGE_PIN AA14 [get_ports {LA1_11}]
set_property PACKAGE_PIN Y15 [get_ports {LA1_12}]
set_property PACKAGE_PIN AA15 [get_ports {LA1_13}]
set_property PACKAGE_PIN AB15 [get_ports {LA1_14}]
set_property PACKAGE_PIN AB16 [get_ports {LA1_15}]

set_property IOSTANDARD LVCMOS33 [get_ports {LACK1}]
set_property PACKAGE_PIN W16 [get_ports {LACK1}]

set_property IOSTANDARD LVCMOS33 [get_ports {CFD_OUT}]
set_property PACKAGE_PIN Y16 [get_ports {CFD_OUT}]

set_property IOSTANDARD LVCMOS33 [get_ports {Gate_STR1_o}]
set_property PACKAGE_PIN Y13 [get_ports {Gate_STR1_o}]

## Bank 85
set_property IOSTANDARD LVCMOS33 [get_ports {LA0_*}]
set_property PACKAGE_PIN C11 [get_ports {LA0_0}]
set_property PACKAGE_PIN B11 [get_ports {LA0_1}]
set_property PACKAGE_PIN D11 [get_ports {LA0_2}]
set_property PACKAGE_PIN B10 [get_ports {LA0_3}]
set_property PACKAGE_PIN A10 [get_ports {LA0_4}]
set_property PACKAGE_PIN D10 [get_ports {LA0_5}]
set_property PACKAGE_PIN B9 [get_ports {LA0_6}]
set_property PACKAGE_PIN A9 [get_ports {LA0_7}]
set_property PACKAGE_PIN C9 [get_ports {LA0_8}]
set_property PACKAGE_PIN D9 [get_ports {LA0_9}]
set_property PACKAGE_PIN E10 [get_ports {LA0_10}]
set_property PACKAGE_PIN E11 [get_ports {LA0_11}]
set_property PACKAGE_PIN F9 [get_ports {LA0_12}]
set_property PACKAGE_PIN F10 [get_ports {LA0_13}]
set_property PACKAGE_PIN G9 [get_ports {LA0_14}]
set_property PACKAGE_PIN G10 [get_ports {LA0_15}]

set_property IOSTANDARD LVCMOS33 [get_ports {LACK0}]
set_property PACKAGE_PIN G11 [get_ports {LACK0}]